[package]
name = "autharie-control-plane"
description = "Autharie Control Plane"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
autharie-api = { path = "../../libs/autharie-api" }
clap = { version = "4.5.54", features = ["derive", "env"] }
dotenvy = "0.15.7"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.44"
