[workspace]
resolver = "2"
members = [
    "apps/control-plane",
    "apps/operator",

    "libs/autharie-core",
    "libs/autharie-api",
    "libs/autharie-auth",
    "libs/autharie-permission",
    "libs/autharie-operator-core",
    "libs/autharie-crds",
    "libs/autharie-amqp",
    "libs/autharie-macros", "libs/herald-core", "libs/autharie-persistence",
    "libs/autharie-s3",
    "libs/autharie-transit", "libs/autharie-postgres", "libs/autharie-domain", "apps/aegis", "libs/aegis-core", "apps/genesis", "libs/genesis-core", "apps/herald",
    "libs/autharie-ovh",
    "libs/autharie-scaleway",
    "libs/autharie-e2e",
]

[workspace.package]
version = "0.1.0"
authors = ["nathaelb <pro.nathaelbonnal@gmail.com>"]
edition = "2024"
