apiVersion: v1
kind: Service
metadata:
  name: {{ include "autharie-control-plane.fullname" . }}
  labels:
    {{- include "autharie-control-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "autharie-control-plane.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: control-plane
  ports:
    - name: http
      port: {{ .Values.controlPlane.server.port }}
      targetPort: http
