[package]
name = "autharie-operator"
description = "Autharie Operator"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rustls = { version = "0.23", default-features = false, features = ["aws-lc-rs"] }
autharie-operator-core = { path = "../../libs/autharie-operator-core" }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["fmt", "env-filter"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage, coverage_nightly)'] }
