[package]
name = "autharie-macros"
description = "Attribute macros for repository registration and transactional use cases"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.104"
quote = "1.0.42"
syn = { version = "2.0.108", features = ["full"] }
