apiVersion: autharie.dev/v1alpha
kind: IdentityInstanceUpgrade
metadata:
  name: cloud-iam-ferriskey-upgrade-2600
  namespace: test-autharie
spec:
  identityInstanceRef:
    name: cloud-iam-ferriskey
  targetVersion: "0.4.0"
  strategy: rolling
  approved: true
