apiVersion: autharie.fr/v1alpha
kind: IdentityDataplaneUpgrade
metadata:
  name: dataplane-eu-1-upgrade-050
  namespace: test-autharie
spec:
  dataplaneId: dataplane-eu-1
  targetVersion: "0.5.0"
  components:
    - Herald
    - Genesis
  strategy: rolling
  maxUnavailable: 1
