{{- include "autharie-dataplane.validate" . -}}
{{- if and .Values.herald.enabled (not .Values.controlPlane.existingSecret) }}
{{- if or .Values.controlPlane.token .Values.controlPlane.auth.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autharie-dataplane.fullname" . }}-control-plane
  labels:
    {{- include "autharie-dataplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.controlPlane.token }}
  token: {{ . | quote }}
  {{- end }}
  {{- with .Values.controlPlane.auth.clientSecret }}
  client-secret: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}
